name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rails:
    name: Rails tests and linters
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
    defaults:
      run:
        working-directory: backend
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: backend

      - name: Copy database config
        run: cp config/database.ci.yml config/database.yml

      - name: Setup test database
        run: bundle exec rails db:setup

      - name: Run tests
        run: bundle exec rake test

      - name: Run linters
        run: bundle exec rubocop --parallel

  next-flesh:
    name: Next flesh tests and linters
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: next-flesh
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.4
          working-directory: next-flesh

      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn dependency
        uses: actions/cache@v1
        with:
          working-directory: next-flesh
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install packages
        run: yarn install --pure-lockfile

      - name: Run linters
        run: yarn lint
